from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()

HEADER_FILL = PatternFill('solid', fgColor='1F2937')
HEADER_FONT = Font(name='Arial', size=11, bold=True, color='FFFFFF')
ACCENT_FILL = PatternFill('solid', fgColor='111827')
BODY_FONT = Font(name='Arial', size=10, color='E5E7EB')
LINK_FONT = Font(name='Arial', size=10, color='4ADE80', underline='single')
THIN_BORDER = Border(
    bottom=Side(style='thin', color='374151'),
    top=Side(style='thin', color='374151'),
    left=Side(style='thin', color='374151'),
    right=Side(style='thin', color='374151')
)
CENTER = Alignment(horizontal='center', vertical='center', wrap_text=True)
WRAP = Alignment(vertical='top', wrap_text=True)

DATA = [
    ("Manage your inbox","管理你的收件匣","Easy","5m","Automation, Integrations","讓 Codex 找到重要郵件並用你的語氣撰寫回覆。","Have Codex find the emails that matter and write the replies in your voice.","搭配 Gmail 使用 Codex，找到需要處理的郵件，用你的語氣草擬回覆。","Use Codex with Gmail to find emails that need attention, draft responses in your voice, and keep watching for new replies.","希望自動篩選重要郵件的人","People who want Codex to find emails that need attention","檢視收件匣 → 學習偏好 → 排程自動分類 → 整理收件匣","Review inbox → Learn taste → Automate triage → Organize","https://developers.openai.com/codex/use-cases/manage-your-inbox"),
    ("Use your computer with Codex","用 Codex 操控電腦","Easy","5m","Knowledge Work, Workflow","讓 Codex 在 Mac 上點擊、打字和操作應用程式。","Let Codex click, type, and navigate apps on your Mac.","使用 Computer Use 功能，將跨應用程式的多步驟任務交給 Codex。","Use Computer Use to hand off multi-step tasks across Mac apps, windows, and files.","需要跨應用操作的 Mac 任務","Tasks that move across apps, windows, or local files on Mac","開啟 Computer Use → 明確提示 → 觀察修正 → 優化","Turn on → Clear prompt → Watch and correct → Build on","https://developers.openai.com/codex/use-cases/use-your-computer-with-codex"),
    ("Follow a goal","追蹤目標","Advanced","1h","Engineering, Automation","給 Codex 持久性目標來執行長期任務。","Give Codex a durable objective for long-running work.","設定跨工作階段的持久性目標，讓 Codex 定期檢查來源並主動回報。","Give Codex a durable objective that persists across sessions and surfaces progress.","需持續數天或數週追蹤的目標","Objectives spanning days or weeks needing regular check-ins","定義目標 → 設定排程 → 檢視優化","Define goal → Set schedule → Review and refine","https://developers.openai.com/codex/use-cases/follow-goals"),
    ("Set up a teammate","設定 AI 隊友","Advanced","1h","Automation, Integrations","讓 Codex 持續監控你的工作並主動通知變更。","Give Codex a durable view of your work so it can notice what changed.","設定 Codex 為持續工作的隊友，監控連接的工具並主動通知變更。","Configure Codex as a persistent teammate that watches your tools and surfaces changes.","需持續監控工具的團隊","Teams wanting persistent monitoring of Slack, Linear, GitHub","連接工具 → 定義範圍 → 設定通知 → 迭代","Connect tools → Define scope → Set notifications → Iterate","https://developers.openai.com/codex/use-cases/proactive-teammate"),
    ("Turn feedback into actions","將回饋轉化為行動","Easy","30m","Data, Integrations","將多來源回饋整合成可審閱文件。","Synthesize feedback from multiple sources into a reviewable artifact.","從 Slack、Linear 等彙整回饋，產出含主題和建議行動的文件。","Pull feedback from Slack, Linear, surveys into a single artifact with themes and next steps.","從多管道收集回饋的產品團隊","Product teams collecting feedback from multiple channels","收集來源 → 歸納主題 → 建立文件 → 迭代","Gather sources → Synthesize → Create artifact → Iterate","https://developers.openai.com/codex/use-cases/feedback-synthesis"),
    ("Clean and prepare messy data","清理雜亂數據","Easy","5m","Data, Knowledge Work","處理表格數據，不影響原始檔案。","Process tabular data without affecting the original.","拖入雜亂 CSV，讓 Codex 產生清理後的副本。","Drag in a messy CSV, describe problems, and Codex writes a cleaned copy.","日期混亂、重複或缺值的資料","CSV exports with mixed dates, duplicates, or missing values","介紹 → 使用方式","Introduction → How to use","https://developers.openai.com/codex/use-cases/clean-messy-data"),
    ("Query tabular data","查詢表格數據","Easy","30m","Data, Knowledge Work","對 CSV、試算表或數據資料夾提問。","Ask a question about a CSV, spreadsheet, or data folder.","搭配數據檔案使用 Codex，回答問題、建立圖表並儲存結果。","Use Codex with data files to answer questions, create visualizations, and save results.","可透過計算或圖表回答的問題","Questions answered through calculation, chart, or summary","使用方式 → 提示","How to use → Tips","https://developers.openai.com/codex/use-cases/analyze-data-export"),
    ("Review GitHub pull requests","審查 GitHub PR","Easy","30m","Integrations, Workflow","在人工審查前捕捉迴歸錯誤。","Catch regressions and potential issues before human review.","連接 Codex 到 GitHub，審查 PR、標記問題、檢查覆蓋率。","Connect Codex to GitHub to review PRs, flag regressions, check test coverage.","需初步審查的工程團隊","Engineering teams wanting first-pass review before human review","使用方式 → 提示","How to use → Tips","https://developers.openai.com/codex/use-cases/github-code-reviews"),
    ("Build responsive front-end designs","建構響應式前端設計","Advanced","1h","Front-end, Design","將截圖轉為響應式 UI 並驗證。","Turn screenshots into responsive UI with visual checks.","將截圖和視覺參考轉化為響應式 UI，內建視覺驗證步驟。","Turn screenshots and visual references into responsive UI with visual verification.","希望將設計稿轉為 UI 的設計師","Designers converting mockups into working UI","提供參考 → 生成 UI → 視覺驗證 → 迭代","Provide references → Generate UI → Verify → Iterate","https://developers.openai.com/codex/use-cases/frontend-designs"),
    ("Understand large codebases","理解大型程式碼庫","Easy","30m","Engineering, Analysis","追蹤請求流程、映射模組。","Trace request flows, map modules, find files fast.","使用 Codex 瀏覽不熟悉的倉庫，追蹤流程、映射依賴。","Navigate unfamiliar repos, trace request flows, map dependencies.","加入新團隊的工程師","Engineers joining a new team or repository","指向倉庫 → 架構問題 → 追蹤流程 → 建立圖","Point at repo → Ask questions → Trace flows → Build map","https://developers.openai.com/codex/use-cases/codebase-onboarding"),
    ("Build a Mac app shell","建構 Mac 應用框架","Advanced","1h","macOS, Code","用 Codex 建構 SwiftUI 應用框架。","Build a Mac-native SwiftUI app shell.","搭建含側邊欄、詳情面板、檢查器和快捷鍵的 Mac 應用。","Scaffold a Mac-native SwiftUI app with sidebar, detail pane, inspector, and shortcuts.","開發 Mac 原生工具的開發者","Developers building Mac-native productivity tools","建構場景 → 側邊欄 → 工具列快捷鍵 → 設定 → 驗證","Scene model → Sidebar → Commands → Settings → Validate","https://developers.openai.com/codex/use-cases/macos-sidebar-detail-inspector"),
    ("Automate bug triage","自動化 Bug 分類","","1h","Automation, Quality","將 Bug 報告轉為優先順序清單。","Turn bug reports into a prioritized list, automate the sweep.","收集多來源 Bug 報告，分類排序並排程自動化分類。","Collect bug reports, categorize, prioritize, and automate triage on schedule.","Bug 量大的 QA 和工程團隊","QA and engineering teams with high bug volume","掃描 → 報告 → 自動化 → 路由追蹤","Sweep → Report → Automate → Route follow-ups","https://developers.openai.com/codex/use-cases/automation-bug-triage"),
    ("Generate slide decks","生成簡報","Easy","30m","Data, Integrations","操作 pptx 並用圖片生成自動化簡報。","Manipulate pptx and use image generation for slides.","建立或修改 PowerPoint，從數據或範本自動化製作簡報。","Create or modify PowerPoint files, generate images, automate deck creation.","需從數據製作簡報的團隊","Teams producing slide decks from data or templates","來源簡報 → 保持可編輯 → 生成視覺 → 驗證","Source deck → Keep editable → Generate visuals → Validate","https://developers.openai.com/codex/use-cases/generate-slide-decks"),
    ("Kick off coding tasks from Slack","從 Slack 啟動程式任務","Easy","5m","Integrations, Workflow","將 Slack 對話轉為雲端任務。","Turn Slack threads into scoped cloud tasks.","在 Slack 中提及 Codex，將討論轉為雲端程式任務。","Mention Codex in Slack to turn discussion into a scoped coding task.","在 Slack 討論程式變更的團隊","Teams discussing code changes in Slack","使用方式 → 提示","How to use → Tips","https://developers.openai.com/codex/use-cases/slack-coding-tasks"),
    ("Make granular UI changes","精細 UI 修改","Easy","5m","Front-end, Design","用 Codex-Spark 快速調整 UI。","Use Codex-Spark for fast UI iteration.","小幅 UI 調整——修改按鈕、間距、文案。","Small, targeted UI changes — tweak buttons, spacing, copy.","進行小幅 UI 調整的開發者","Developers making small UI tweaks","選擇模型 → 開發流程 → 簡短提示 → 何時放慢","Pick model → Dev flow → Small prompts → When to slow down","https://developers.openai.com/codex/use-cases/make-granular-ui-changes"),
    ("Coordinate new-hire onboarding","協調新人入職","","30m","Integrations, Data","準備入職追蹤表和迎新草稿。","Prepare onboarding trackers and welcome-space drafts.","收集新人資訊、更新追蹤表、草擬摘要。","Gather new-hire context, stage tracker updates, draft summaries.","人資、招募、IT 團隊","People, recruiting, IT, or workplace operations teams","定義範圍 → 收集資訊 → 追蹤表 → 摘要 → 每週流程","Define boundary → Gather inputs → Tracker → Summaries → Weekly","https://developers.openai.com/codex/use-cases/new-hire-onboarding"),
    ("Learn a new concept","學習新概念","","30m","Knowledge Work, Data","將密集素材轉為學習報告。","Turn dense material into a learning report.","研讀論文或課程，分段進行並產出報告。","Study papers or courses, split into sessions, produce learning report.","學習新領域的專業人士","Professionals learning new domains","研讀 → 深入 → 應用","Study → Deep dive → Apply","https://developers.openai.com/codex/use-cases/learn-a-new-concept"),
    ("Upgrade your API integration","升級 API 整合","Advanced","1h","Evaluation, Engineering","升級到最新 OpenAI API 模型。","Upgrade your app to the latest OpenAI API models.","遷移到最新模型，更新端點和參數。","Migrate from older API versions, update endpoints and parameters.","維護 OpenAI API 整合的團隊","Teams maintaining OpenAI API integrations","檢查整合 → 遷移計畫 → 遷移驗證","Inspect integration → Migration plan → Migrate and verify","https://developers.openai.com/codex/use-cases/api-integration-migrations"),
    ("Deploy an app or website","部署應用或網站","Easy","30m","Front-end, Integrations","部署預覽並取得線上 URL。","Build or update a web app, deploy, get a live URL.","建構或更新網頁應用，部署預覽版本。","Build or update a web app, deploy a preview, get a shareable URL.","想快速上線的開發者","Developers wanting code to live preview quickly","使用方式 → 提示","How to use → Tips","https://developers.openai.com/codex/use-cases/deploy-app-or-website"),
    ("Turn Figma designs into code","Figma 設計轉程式碼","Advanced","1h","Front-end, Design","將 Figma 選取轉為精緻 UI。","Turn Figma selections into polished UI.","從 Figma 匯出設計脈絡，生成可用於正式環境的 UI 元件。","Export from Figma, generate production-ready UI with visual verification.","重視還原度的設計轉碼流程","Design-to-code workflows where fidelity matters","匯出 → 生成 → 驗證 → 迭代","Export → Generate → Verify → Iterate","https://developers.openai.com/codex/use-cases/figma-designs-to-code"),
    ("QA your app with Computer Use","用 Computer Use 測試應用","Advanced","1h","Automation, Quality","點擊真實產品流程並記錄問題。","Click through real product flows and log what breaks.","讓 Codex 點擊應用 UI 流程、測試互動並記錄問題。","Have Codex click through UI flows, test interactions, and log issues.","想要自動化探索性測試的 QA 團隊","QA teams wanting automated exploratory testing","使用方式","How to use","https://developers.openai.com/codex/use-cases/qa-your-app-with-computer-use"),
    ("Analyze datasets and ship reports","分析數據並產出報告","Easy","30m","Data, Analysis","將雜亂數據轉為分析和視覺化。","Turn messy data into clear analysis and visualizations.","分析數據集、建立視覺化圖表並產出可分享的報告。","Analyze datasets, create visualizations, produce shareable reports.","需從原始數據產出報告的分析師","Analysts needing reports from raw data","使用方式 → 提示","How to use → Tips","https://developers.openai.com/codex/use-cases/datasets-and-reports"),
    ("Complete tasks from messages","從訊息完成任務","Easy","5m","Knowledge Work, Integrations","將 iMessage 對話轉為已完成工作。","Turn iMessage threads into completed work.","讀取 iMessage，提取待辦並在連接的應用中完成。","Read iMessage threads, extract action items, complete them across apps.","透過 iMessage 接收工作請求的人","People receiving work requests via iMessage","使用方式","How to use","https://developers.openai.com/codex/use-cases/complete-tasks-from-messages"),
    ("Get from idea to proof of concept","從想法到概念驗證","Easy","30m","Front-end, Engineering","用圖片生成探索概念並建構第一版。","Explore concept visually with ImageGen, build first version.","搭配圖片生成使用 Codex 視覺化探索並建構概念驗證。","Use Codex with image generation to explore and build a proof of concept.","探索新想法的創辦人和團隊","Founders and product teams exploring new ideas","使用方式","How to use","https://developers.openai.com/codex/use-cases/idea-to-proof-of-concept"),
    ("Create browser game prototypes","建立瀏覽器遊戲原型","Advanced","1h","Front-end, Engineering","定義遊戲計畫讓 Codex 建構和測試。","Define a game plan, let Codex build and test it.","描述概念，讓 Codex 建構可遊玩的瀏覽器原型。","Describe a game concept, Codex builds a playable browser prototype.","進行遊戲機制原型的設計師","Game designers prototyping mechanics","定義概念 → 首個循環 → 迭代玩法","Define concept → First loop → Iterate gameplay","https://developers.openai.com/codex/use-cases/browser-game-prototyping"),
    ("Use Codex as an evaluator","將 Codex 用作評估器","Advanced","1h","Evaluation, Engineering","用 Codex 作為評分改進迴圈。","Use Codex as a scored improvement loop.","在回饋迴圈中讓 Codex 評估產出、評分並迭代。","Use Codex in a feedback loop to evaluate, score, and iterate.","處理困難最佳化問題的團隊","Teams working on hard optimization problems","定義標準 → 執行迴圈 → 審查交付","Define criteria → Run loop → Review and ship","https://developers.openai.com/codex/use-cases/codex-as-evaluator"),
    ("Save workflows as skills","將工作流儲存為技能","Easy","5m","Engineering, Workflow","建立可重複使用的 Codex 技能。","Create a reusable skill for Codex.","將可運作的對話轉為技能，用於審查規則或腳本。","Turn a working thread into a reusable skill for review rules or scripts.","希望重複使用工作流的團隊","Teams wanting reusable codified workflows","提供素材 → Codex 建立","Provide material → Codex creates","https://developers.openai.com/codex/use-cases/reusable-codex-skills"),
    ("Keep documentation up-to-date","保持文件最新","Easy","30m","Engineering, Code","自動化文件更新。","Use code and sources to automate docs updates.","比對原始碼變更和文件，草擬文件更新。","Compare source changes, docs, release notes, draft documentation updates.","需追蹤變更的開發者文件","Developer docs needing to track behavior changes","介紹 → 使用方式","Introduction → How to use","https://developers.openai.com/codex/use-cases/update-documentation"),
    ("Build for iOS","開發 iOS 應用","Advanced","1h","iOS, Code","搭建和除錯 SwiftUI 應用。","Scaffold, build, and debug SwiftUI apps.","搭建 iPhone/iPad SwiftUI 應用，搭配模擬器測試。","Scaffold, build, debug SwiftUI apps with iOS plugin for simulator testing.","開發新應用的 iOS 開發者","iOS developers building new apps or features","搭建 → 建構畫面 → 除錯測試 → 提示","Scaffold → Build screens → Debug → Tips","https://developers.openai.com/codex/use-cases/native-ios-apps"),
    ("Refactor your codebase","重構程式碼庫","Advanced","1h","Engineering, Code","移除死碼並現代化舊模式。","Remove dead code and modernize legacy patterns.","識別死碼、現代化舊模式，不改變外部行為。","Identify dead code, modernize legacy patterns without changing behavior.","累積技術債的工程團隊","Engineering teams with accumulated technical debt","了解全貌 → 規劃重構 → 安全執行","Understand landscape → Plan → Execute safely","https://developers.openai.com/codex/use-cases/refactor-your-codebase"),
    ("Add iOS app intents","新增 iOS App Intents","Advanced","1h","iOS, Code","讓操作可供捷徑、Siri 使用。","Make actions available to Shortcuts, Siri, Spotlight.","透過 App Intents 將關鍵操作暴露給 iOS 系統。","Expose key actions to iOS system through App Intents.","想要系統級整合的 iOS 開發者","iOS developers wanting system-level integration","操作和實體 → 系統介面 → 應用模式 → 提示","Actions/entities → System surfaces → App pattern → Tips","https://developers.openai.com/codex/use-cases/ios-app-intents"),
    ("Build for macOS","開發 macOS 應用","Advanced","1h","macOS, Code","搭建原生 Mac 應用。","Scaffold, build, and debug native Mac apps.","搭建含選單、工具列和多視窗的原生 Mac 應用。","Scaffold native Mac apps with menus, toolbars, and multi-window.","開發 Mac 原生工具的開發者","macOS developers building native productivity tools","搭建 → 桌面 UI → 除錯 → 提示","Scaffold → Desktop UI → Debug → Tips","https://developers.openai.com/codex/use-cases/native-macos-apps"),
    ("Adopt liquid glass","採用 Liquid Glass","Advanced","1h","iOS, Code","遷移到 iOS 26 Liquid Glass。","Migrate SwiftUI app to Liquid Glass with iOS 26.","將現有 SwiftUI 應用遷移到 iOS 26 Liquid Glass 設計語言。","Migrate existing SwiftUI app to Liquid Glass design language in iOS 26.","為 iOS 26 更新應用的開發者","iOS developers updating apps for iOS 26","iOS 26 基準 → iOS 外掛 → 遷移計畫 → 提示","iOS 26 baseline → iOS plugin → Migration plan → Tips","https://developers.openai.com/codex/use-cases/ios-liquid-glass"),
    ("Add Mac telemetry","新增 Mac 遙測","Advanced","30m","macOS, Code","用 Logger 加入遙測並驗證。","Instrument a feature with Logger and verify.","透過 Apple Logger 新增結構化日誌。","Add structured logging using Apple's Logger framework.","需可觀測性的 Mac 開發者","Mac developers needing observability","加入 Logger → 保持精簡 → 證明事件 → 保存追蹤","Add Logger → Keep small → Prove event → Save trace","https://developers.openai.com/codex/use-cases/macos-telemetry-logs"),
    ("Debug in iOS simulator","iOS 模擬器除錯","Advanced","1h","iOS, Code","用 XcodeBuildMCP 在模擬器除錯。","Drive app in iOS Simulator with XcodeBuildMCP.","在模擬器中重現 Bug、擷取證據並修復。","Run app in simulator, reproduce bugs, capture evidence, fix issues.","除錯模擬器問題的 iOS 開發者","iOS developers debugging simulator-reproducible issues","模擬器迴圈 → 重現 Bug → 修復驗證","Simulator loop → Reproduce → Fix and verify","https://developers.openai.com/codex/use-cases/ios-simulator-bug-debugging"),
    ("Audit dependency incidents","審查依賴事件","Easy","30m","Engineering, Quality","將安全公告轉為審查計畫。","Turn package advisory into a repo-audit plan.","找到受影響的依賴並建立優先修復計畫。","Find affected dependencies, create prioritized remediation plan.","回應漏洞的安全團隊","Security teams responding to vulnerabilities","介紹 → 使用方式","Introduction → How to use","https://developers.openai.com/codex/use-cases/dependency-incident-audits"),
    ("Prepare meeting briefs","準備會議簡報","Easy","30m","Integrations, Knowledge Work","將行事曆轉為議程和筆記。","Turn calendar context into agenda and notes.","從行事曆和工具中提取脈絡，準備會議簡報。","Pull context from calendar and tools to prepare meeting briefs.","參加大量會議的專業人士","Professionals attending many meetings","介紹 → 使用方式","Introduction → How to use","https://developers.openai.com/codex/use-cases/meeting-prep-briefs"),
    ("Run event playbooks","執行活動 Playbook","Easy","30m","Integrations, Knowledge Work","建立可重複的活動工作流。","Create repeatable workflows for events.","建立和執行可重複的活動規劃和協調 Playbook。","Create and run repeatable playbooks for event planning.","活動協調者和專案經理","Event coordinators and program managers","使用方式","How to use","https://developers.openai.com/codex/use-cases/event-launch-playbooks"),
    ("Run code migrations","執行程式碼遷移","Advanced","1h","Engineering, Code","在受控檢查點中遷移舊堆疊。","Migrate legacy stacks in controlled checkpoints.","規劃並在受控檢查點中執行遷移。","Plan and execute migrations in controlled checkpoints.","遷移框架或語言的工程團隊","Engineering teams migrating frameworks or languages","介紹 → 使用方式","Introduction → How to use","https://developers.openai.com/codex/use-cases/code-migrations"),
    ("Refactor SwiftUI screens","重構 SwiftUI 畫面","Advanced","1h","iOS, Code","拆分過大的 SwiftUI 畫面。","Split oversized SwiftUI screens into subviews.","將大型視圖拆解為小子視圖，保持行為不變。","Decompose large SwiftUI views into smaller subviews preserving behavior.","SwiftUI 視圖過大的開發者","iOS developers with oversized SwiftUI views","辨識視圖 → 規劃拆解 → 提取 → 驗證","Identify → Plan → Extract → Verify","https://developers.openai.com/codex/use-cases/ios-swiftui-view-refactor"),
    ("Draft PRDs from internal context","從內部脈絡草擬 PRD","Easy","30m","Integrations, Knowledge Work","從 Linear、Slack 等建立 PRD。","Create PRDs from Linear, Slack, docs, meeting notes.","搭配 Linear、Slack、Notion 建立包含時程和決策的 PRD。","Use connected apps to create PRD with timeline, decisions, open questions.","將規劃脈絡轉為 PRD 的團隊","Product teams turning planning context into a PRD","選擇來源 → 精煉 → 檢查來源","Choose sources → Refine → Check trail","https://developers.openai.com/codex/use-cases/draft-prds-from-sources"),
    ("Forecast cash flow","預測現金流","","30m","Data, Knowledge Work","建立可編輯的現金流預測工作簿。","Find liquidity low point in a forecast workbook.","提供輸入和限制，建立標記安全餘額違規的工作簿。","Provide inputs and constraints, create workbook flagging safety-balance breaches.","建立現金流預測的財務團隊","Finance teams creating cash flow projections","使用方式","How to use","https://developers.openai.com/codex/use-cases/cash-flow-forecast"),
    ("Model a DCF valuation","建構 DCF 估值模型","","30m","Data, Knowledge Work","將財務輸入轉為估值工作簿。","Turn financial inputs into a valuation workbook.","產出含 WACC 和敏感度分析的 DCF 估值工作簿。","Produce DCF workbook with revenue drivers, WACC, and sensitivity tables.","需要 DCF 模型的財務專業人士","Finance and investment professionals","使用方式","How to use","https://developers.openai.com/codex/use-cases/dcf-model"),
    ("Review budget vs. actuals","審查預算與實際比較","","30m","Data, Knowledge Work","建立差異分析工作簿。","Turn plan and actuals into a variance workbook.","建立含說明和行動項目的差異分析工作簿。","Create variance analysis workbook with explanations and action items.","進行結算的財務團隊","Finance teams doing monthly or quarterly close","使用方式","How to use","https://developers.openai.com/codex/use-cases/budget-vs-actuals-review"),
    ("Add evals to your AI application","為 AI 應用新增評估","Advanced","1h","Evaluation, Quality","建立 Promptfoo 評估套件。","Turn expected behavior into a Promptfoo eval suite.","從預期行為建立評估套件，然後執行和迭代。","Create Promptfoo eval suite from expected behaviors, run and iterate.","需系統性評估的 AI 開發者","AI developers needing systematic evaluation","介紹 → 使用方式","Introduction → How to use","https://developers.openai.com/codex/use-cases/ai-app-evals"),
    ("Turn user stories into UI mocks","使用者故事轉 UI 模型","Easy","30m","Integrations, Knowledge Work","將回饋轉為團隊可回應的模型。","Convert feedback into mockups teams can react to.","收集回饋，整理為使用者故事，生成 UI 模型。","Gather feedback, normalize into stories, generate UI mockups with ImageGen.","將回饋轉為視覺方向的團隊","Product teams turning feedback into visual direction","生成視覺 → 模型轉原型","Generate visual truth → Mock to prototype","https://developers.openai.com/codex/use-cases/user-stories-to-ui-mocks"),
    ("Bring your app to ChatGPT","將應用帶入 ChatGPT","","","Integrations, Code","將使用場景轉為 ChatGPT 應用。","Turn use cases into focused ChatGPT apps.","使用 Codex 將使用場景轉為 ChatGPT 專用應用。","Use Codex to turn use cases into focused apps for ChatGPT.","開發 ChatGPT 應用的開發者","Developers building ChatGPT plugins or apps","建構什麼 → 為何適合 → 使用方式 → 提示","What → Why Codex fits → How → Tips","https://developers.openai.com/codex/use-cases/chatgpt-apps"),
    ("Build React Native apps with Expo","用 Expo 建構 React Native","Advanced","1h","Mobile, Engineering","從想法到可運作的 Expo 應用。","Go from idea to a working Expo app.","搭配 Expo 外掛從想法到可運作的 React Native 應用。","Use Codex with Expo plugin from idea to working React Native app.","開發跨平台應用的行動開發者","Mobile developers building cross-platform apps","搭建 → 建構畫面 → 裝置測試 → 迭代","Scaffold → Build screens → Test → Iterate","https://developers.openai.com/codex/use-cases/react-native-expo-apps"),
    ("Create a CLI Codex can use","建立 Codex 可用的 CLI","Easy","30m","Engineering, Code","建立可組合的命令工具。","Give Codex a composable command tool.","建構 Codex 可在工作流中呼叫的 CLI 工具。","Build a CLI tool Codex can invoke in workflows.","希望與內部工具互動的團隊","Teams wanting Codex to interact with internal tools","設計介面 → 建構 → 註冊技能 → 測試","Design → Build → Register skill → Test","https://developers.openai.com/codex/use-cases/agent-friendly-clis"),
    ("Prioritize Slack action items","排序 Slack 待辦事項","Easy","5m","Automation, Integrations","將 Slack 對話轉為排序待辦佇列。","Turn Slack threads into a ranked queue.","掃描 Slack 對話，提取待辦並按優先級排序。","Scan Slack threads, extract action items, rank by priority.","透過 Slack 接收大量待辦的人","Professionals receiving many action items via Slack","使用方式","How to use","https://developers.openai.com/codex/use-cases/slack-action-triage"),
    ("Run verified operations","執行已驗證的操作","Easy","30m","Automation, Integrations","執行可重複工作流並驗證結果。","Run repeatable workflows and verify results.","執行含內建驗證步驟的操作工作流。","Run operational workflows with built-in verification steps.","執行週期性工作流的營運團隊","Operations teams running recurring workflows","使用方式","How to use","https://developers.openai.com/codex/use-cases/verified-operations-workflows"),
    ("Turn meetings into follow-ups","將會議轉為後續行動","Easy","5m","Automation, Integrations","將 Zoom 會議轉為跨工具行動。","Convert Zoom meeting insights into actions.","處理 Zoom 逐字稿，提取待辦並建立後續任務。","Process Zoom transcripts, extract action items, create follow-up tasks.","參加大量會議的專業人士","Professionals attending many meetings","使用方式","How to use","https://developers.openai.com/codex/use-cases/zoom-meeting-follow-ups"),
]

HEADERS_ZH = ["#","英文名稱","中文名稱","難度","時間","分類","中文簡述","英文簡述","中文概述","英文概述","中文適用場景","英文適用場景","中文步驟","英文步驟","官方連結"]
HEADERS_EN = ["#","Name (EN)","Name (ZH)","Difficulty","Time","Categories","Description (ZH)","Description (EN)","Overview (ZH)","Overview (EN)","Best For (ZH)","Best For (EN)","Steps (ZH)","Steps (EN)","Official URL"]
COL_WIDTHS = [4,32,20,10,8,22,30,30,40,40,30,30,35,35,50]

def style_sheet(ws, headers):
    for col_idx, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=h)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = CENTER
        cell.border = THIN_BORDER

    for row_idx, row_data in enumerate(DATA, 2):
        fill = ACCENT_FILL if row_idx % 2 == 0 else PatternFill('solid', fgColor='0D1117')
        for col_idx, val in enumerate(row_data, 1):
            cell = ws.cell(row=row_idx, column=col_idx + 1, value=val)
            cell.font = BODY_FONT
            cell.fill = fill
            cell.alignment = WRAP
            cell.border = THIN_BORDER
        num_cell = ws.cell(row=row_idx, column=1, value=row_idx - 1)
        num_cell.font = Font(name='Arial', size=10, color='4ADE80')
        num_cell.fill = fill
        num_cell.alignment = CENTER
        num_cell.border = THIN_BORDER
        link_cell = ws.cell(row=row_idx, column=len(headers))
        link_cell.font = LINK_FONT

    for i, w in enumerate(COL_WIDTHS, 1):
        ws.column_dimensions[get_column_letter(i)].width = w

    ws.freeze_panes = 'A2'
    ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}{len(DATA)+1}"

ws_zh = wb.active
ws_zh.title = "中文版"
ws_zh.sheet_properties.tabColor = "4ADE80"
style_sheet(ws_zh, HEADERS_ZH)

ws_en = wb.create_sheet("English")
ws_en.sheet_properties.tabColor = "9CA3AF"
style_sheet(ws_en, HEADERS_EN)

out = "/Users/weifengchnag/projects/Personal/output/codex-use-cases.xlsx"
wb.save(out)
print(f"Saved to {out}")
